### ISSUE TITLE
Handle exception for pixanos event on websocket

### ISSUE THREAD

**Issue by Cypherpunk1337** [Dellenoam/NotPixelBot#17]
```
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\0xFFFFFFFF\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Users\0xFFFFFFFF\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 250-251: character maps to <undefined>
Call stack:
  File "C:\Users\0xFFFFFFFF\Desktop\NotPixelBot\main.py", line 14, in <module>
    asyncio.run(main())
  File "C:\Users\0xFFFFFFFF\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\0xFFFFFFFF\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\0xFFFFFFFF\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\0xFFFFFFFF\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\0xFFFFFFFF\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
  File "C:\Users\0xFFFFFFFF\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\0xFFFFFFFF\Desktop\NotPixelBot\bot\core\canvas_updater\websocket_manager.py", line 265, in _connect_websocket
    await self._handle_websocket_connection()
  File "C:\Users\0xFFFFFFFF\Desktop\NotPixelBot\bot\core\canvas_updater\websocket_manager.py", line 345, in _handle_websocket_connection
    await self._handle_websocket_message(decoded_message)
  File "C:\Users\0xFFFFFFFF\Desktop\NotPixelBot\bot\core\canvas_updater\websocket_manager.py", line 381, in _handle_websocket_message
    self._canvas_renderer.update_canvas(message)
  File "C:\Users\0xFFFFFFFF\Desktop\NotPixelBot\bot\core\canvas_updater\dynamic_canvas_renderer.py", line 97, in update_canvas
    self._process_event_message(pixels_data["data"])
  File "C:\Users\0xFFFFFFFF\Desktop\NotPixelBot\bot\core\canvas_updater\dynamic_canvas_renderer.py", line 108, in _process_event_message
    dev_logger.info(f"Received Pixanos event: {event}")
Message: 'Received Pixanos event: {\'type\': \'Pixanos\', \'data\': \'{"info":{"seed":1432712011,"percentage":0.5,"color":"#171F2A"},"user":{"userId":1001471347,"firstName":"H","lastName":"AlBloushi▪️","userPic":"https://npx-cdn.fra1.digitaloceanspaces.com/userpics/f3a53253caf54ba6.jpg","squad":{""squadId":577266,"slug":"DictatorCrypto","name":"Dictator Crypto","logo":"https://cdn.joincommunity.xyz/api-clicker/tg/team-avatars/578940.jpg"}}}\'}'
Arguments: ()
2024-12-01 02:32:08 | WARNING  | WebSocketManager | Unknown WebSocket error occurred while handling message
2024-12-01 02:32:09 | WARNING  | WebSocketManager | Connection attempt 1 failed, retrying in 5 seconds
```

**Comment by Dellenoam** [comment]
Should be fixed now
