### ISSUE TITLE
Exception: Error while getting info about me

### ISSUE THREAD

**Issue by Rippa-cmd** [Dellenoam/NotPixelBot#25]
Hello!
Pls let me know how to fix it. After git pull it appeared.

`2024-12-03 20:16:20 | ERROR | [notpxbot.py](https://notpxbot.py/) | Line 1345 | mmainac | Traceback (most recent call last):
  File "/root/NotPixelBot/.venv/lib/python3.12/site-packages/aiohttp/client_[reqrep.py](https://reqrep.py/)", line 1055, in start
    message, payload = await [protocol.read](https://protocol.read/)()  # type: ignore[union-attr]
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/root/NotPixelBot/.venv/lib/python3.12/site-packages/aiohttp/[streams.py](https://streams.py/)", line 667, in read
    await self._waiter
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/NotPixelBot/bot/core/[notpxbot.py](https://notpxbot.py/)", line 400, in _get_me
    response = await session.get(
               ^^^^^^^^^^^^^^^^^^
  File "/root/NotPixelBot/.venv/lib/python3.12/site-packages/aiohttp/[client.py](https://client.py/)", line 728, in _request
    await resp.start(conn)
  File "/root/NotPixelBot/.venv/lib/python3.12/site-packages/aiohttp/client_[reqrep.py](https://reqrep.py/)", line 1050, in start
    with self._timer:
  File "/root/NotPixelBot/.venv/lib/python3.12/site-packages/aiohttp/[helpers.py](https://helpers.py/)", line 671, in exit
    raise asyncio.TimeoutError from exc_val
TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/NotPixelBot/bot/core/[notpxbot.py](https://notpxbot.py/)", line 158, in run
    next_iteration_sleep_time = await self._perform_notpx_actions(
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/NotPixelBot/bot/core/[notpxbot.py](https://notpxbot.py/)", line 242, in _perform_notpx_actions
    about_me_data = await self._get_me(session)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/NotPixelBot/bot/core/[notpxbot.py](https://notpxbot.py/)", line 416, in _get_me
    return await self._get_me(session=session, attempts=attempts + 1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/NotPixelBot/bot/core/[notpxbot.py](https://notpxbot.py/)", line 416, in _get_me
    return await self._get_me(session=session, attempts=attempts + 1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/NotPixelBot/bot/core/[notpxbot.py](https://notpxbot.py/)", line 416, in _get_me
    return await self._get_me(session=session, attempts=attempts + 1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/NotPixelBot/bot/core/[notpxbot.py](https://notpxbot.py/)", line 417, in _get_me
    raise Exception(f"{self.session_name} | Error while getting info about me")
Exception: mmainac | Error while getting info about me`

**Comment by Dellenoam** [comment]
it was notpixel server issue (lags)
