### ISSUE TITLE
Failed to send tganalytics

### ISSUE THREAD

**Issue by mo13ammad** [Dellenoam/NotPixelBot#4]
`2024-11-13 20:23:29 | WARNING  | mohammad | Failed to send tganalytics event, retrying in 5 seconds | Attempts: 1
2024-11-13 20:23:34 | WARNING  | mohammad | Failed to send tganalytics event, retrying in 5 seconds | Attempts: 2
2024-11-13 20:23:39 | WARNING  | mohammad | Failed to send tganalytics event, retrying in 5 seconds | Attempts: 3
2024-11-13 20:23:44 | ERROR    | mohammad | Error while sending tganalytics event
2024-11-13 20:23:44 | INFO     | mohammad | Retrying in 60 seconds
`

this happend for every account and not start to paint

**Comment by Dellenoam** [comment]
Can you share the latest logs from dev_logs.log?

**Comment by mo13ammad** [comment]
telegram is ban in my country but i use router ro acess to teelgram and telegram ip
can u say what is address or domain for connect to tg service use in code ?

`Traceback (most recent call last):
  File "/home/jatajar/NotPixelBot/bot/core/notpxbot.py", line 243, in _send_tganalytics_event
    response = await session.get(
               ^^^^^^^^^^^^^^^^^^
  File "/home/jatajar/.venv/lib/python3.12/site-packages/aiohttp/client.py", line 661, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jatajar/.venv/lib/python3.12/site-packages/aiohttp/connector.py", line 556, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jatajar/.venv/lib/python3.12/site-packages/aiohttp/connector.py", line 1009, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jatajar/.venv/lib/python3.12/site-packages/aiohttp/connector.py", line 1343, in _create_direct_connection
    raise last_exc
  File "/home/jatajar/.venv/lib/python3.12/site-packages/aiohttp/connector.py", line 1312, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jatajar/.venv/lib/python3.12/site-packages/aiohttp/connector.py", line 1083, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host tganalytics.xyz:443 ssl:default [Connect call failed ('10.10.34.34', 443)]`

**Comment by Dellenoam** [comment]
When a tganalytics event is sent it makes a request to “tganalytics.xyz”. I also noticed that you had “tganalytics.xyz” resolved as "10.10.34.34", which is clearly not true. You can start digging that way
